version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html

permissions:
  - object: /var/www/html/fbl-fe
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 777
    type:
      - directory
      - file

hooks:
  BeforeInstall:
    - location: deploy/before_install.sh
      timeout: 300
      runas: ec2-user