version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/fbl/fe

permissions:
  - object: /home/ec2-user/fbl/fe
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 777
    type:
      - directory
      - file

hooks:
  BeforeInstall:
    - location: deploy/before_install.sh
      timeout: 300
      runas: ec2-user
  After:
    - location: deploy/run.sh
      timeout: 300
      runas: ec2-user